title: Test docs site
description: Seeing how it looks
theme: just-the-docs

url: https://sebanalysis.github.io/docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
